steps:
  # build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$_APPNAME
      - .
    dir: www
    # push image to Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$_APPNAME
    # deploy
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_APPNAME
      - --image
      - gcr.io/$PROJECT_ID/$_APPNAME
      - --platform
      - managed
      - --timeout
      - "300"
      - --region
      - asia-northeast1
      - --memory
      - 1Gi
      - --allow-unauthenticated
images:
  - gcr.io/$PROJECT_ID/$_APPNAME
